/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Toy.java
 *
 * Created on 2011-10-19, 16:22:52
 */
package hoffman;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 简单界面程序，调用已完成的类和方法
 * @author afunx
 */
public class Toy extends javax.swing.JFrame {
    private File srcFile;
    private File dicFile;
    private File codFile;
    private File decFile;
    InputOutput input;
    HoffMan<SimpleBinaryTree> hoffMan;
    /**
     * 默认构造器
     */
    public Toy() {
        initComponents();
    }
    private void dict(){
        try {
            input = new InputOutput();
            srcFile = new File(srcAddJTF.getText());
            dicFile = new File(dicAddJTF.getText());
            input.read(srcFile);
            int size = input.getCodesLength();
            //hoffman编解码器
            hoffMan = new HoffMan(size);
            //把input的码字及概率添加到SimpleBinaryTree对象中
            for(int i=0;i<size;i++){
                String code = String.valueOf(input.getCodes().get(i));
                double probability = (input.getProbability().get(i));
                hoffMan.getFactory().addElement(new SimpleBinaryTree(null,null,null,probability,1,code,true));
                }
             hoffMan.coding();
             //获得字典
              hoffMan.getDictionary().outputFile(dicFile);
        } catch (InstantiationException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void code(){
        try {
            codFile = new File(codAddJTF.getText());
            //编码
            input.code(srcFile,codFile,hoffMan.getDictionary());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void decode(){
        try {
            decFile = new File(decAddJTF.getText());
            input.decode(codFile,decFile,hoffMan.getDictionary());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Toy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcAddJL = new javax.swing.JLabel();
        dicAddJL = new javax.swing.JLabel();
        codAddJL = new javax.swing.JLabel();
        decAddJL = new javax.swing.JLabel();
        srcAddJTF = new javax.swing.JTextField();
        dicAddJTF = new javax.swing.JTextField();
        codAddJTF = new javax.swing.JTextField();
        decAddJTF = new javax.swing.JTextField();
        exeJB = new javax.swing.JButton();
        dicJB = new javax.swing.JButton();
        codJB = new javax.swing.JButton();
        decJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        srcAddJL.setText("原文地址");

        dicAddJL.setText("字典地址");

        codAddJL.setText("编码地址");

        decAddJL.setText("解码地址");

        srcAddJTF.setText("c:/infle.dat");
        srcAddJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcAddJTFActionPerformed(evt);
            }
        });

        dicAddJTF.setText("c:/dict.txt");

        codAddJTF.setText("c:/code.txt");

        decAddJTF.setText("c:/decode.txt");

        exeJB.setText("执行");
        exeJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeJBActionPerformed(evt);
            }
        });

        dicJB.setText("字典化");
        dicJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicJBActionPerformed(evt);
            }
        });

        codJB.setText("编码");
        codJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codJBActionPerformed(evt);
            }
        });

        decJB.setText("解码");
        decJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcAddJL)
                    .addComponent(dicAddJL)
                    .addComponent(codAddJL)
                    .addComponent(decAddJL))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dicAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(decJB, 0, 0, Short.MAX_VALUE)
                    .addComponent(codJB, 0, 0, Short.MAX_VALUE)
                    .addComponent(dicJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exeJB, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcAddJL)
                    .addComponent(srcAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exeJB))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dicAddJL)
                    .addComponent(dicAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dicJB))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codAddJL)
                    .addComponent(codAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codJB))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decAddJL)
                    .addComponent(decAddJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decJB))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeJBActionPerformed
               this.dict();
               this.code();
               this.decode();
}//GEN-LAST:event_exeJBActionPerformed

private void srcAddJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcAddJTFActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_srcAddJTFActionPerformed

private void dicJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicJBActionPerformed
    this.dict();// TODO add your handling code here:
}//GEN-LAST:event_dicJBActionPerformed

private void codJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codJBActionPerformed
    this.code();// TODO add your handling code here:
}//GEN-LAST:event_codJBActionPerformed

private void decJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decJBActionPerformed
    this.decode();// TODO add your handling code here:
}//GEN-LAST:event_decJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toy().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codAddJL;
    private javax.swing.JTextField codAddJTF;
    private javax.swing.JButton codJB;
    private javax.swing.JLabel decAddJL;
    private javax.swing.JTextField decAddJTF;
    private javax.swing.JButton decJB;
    private javax.swing.JLabel dicAddJL;
    private javax.swing.JTextField dicAddJTF;
    private javax.swing.JButton dicJB;
    private javax.swing.JButton exeJB;
    private javax.swing.JLabel srcAddJL;
    private javax.swing.JTextField srcAddJTF;
    // End of variables declaration//GEN-END:variables
}
